In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv('Downloads/covid_toy.csv')

In [6]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [7]:
df.tail()

,age,gender,fever,cough,city,has_covid
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No
99,10,Female,98.0,Strong,Kolkata,Yes


In [8]:
df.sample(5)

,age,gender,fever,cough,city,has_covid
62,56,Female,104.0,Strong,Bangalore,Yes
93,27,Male,100.0,Mild,Kolkata,Yes
82,24,Male,98.0,Mild,Kolkata,Yes
10,75,Female,NaN,Mild,Delhi,No
4,65,Female,101.0,Mild,Mumbai,No


In [9]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [10]:
df['fever'].value_counts()

fever
101.0    17
98.0     17
104.0    14
100.0    13
99.0     10
102.0    10
103.0     9
Name: count, dtype: int64

In [11]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [12]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [13]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns =[ 'has_covid']), df['has_covid'],test_size=0.2)

In [15]:
x_train

,age,gender,fever,cough,city
42,27,Male,100.0,Mild,Delhi
70,68,Female,101.0,Strong,Delhi
58,23,Male,98.0,Strong,Mumbai
28,16,Male,104.0,Mild,Kolkata
13,64,Male,102.0,Mild,Bangalore
...,...,...,...,...,...
40,49,Female,102.0,Mild,Delhi
54,60,Female,99.0,Mild,Mumbai
73,34,Male,98.0,Strong,Kolkata
43,22,Female,99.0,Mild,Bangalore


1. Aam zindagi

In [16]:
#adding simple imputer to fever col
s1 = SimpleImputer()
x_train_fever = s1.fit_transform(x_train[['fever']])

#also the test data
x_test_fever = s1.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [17]:
x_train_fever

array([[100.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [100.94444444],
       [101.        ],
       [100.94444444],
       [ 98.        ],
       [103.        ],
       [100.94444444],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [100.94444444],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [101

In [18]:
#OrdinalEncoding ->Cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

#also test the data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape


(80, 1)

In [29]:
#x_train_cough

In [19]:
#OneHOtEncoding -> gender, city
ohe = OneHotEncoder(drop = 'first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

#also test the data
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape


(80, 4)

In [37]:
#x_train_gender_city

In [20]:
#Extracting age
x_train_age = x_train.drop(columns = ['gender','fever','cough','city']).values

#also test the data
x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values
x_train_age.shape


(80, 1)

In [40]:
#x_train_age

In [22]:
x_train_transformed = np.concatenate((x_train_age,x_train_gender_city,x_train_cough,x_train_fever), axis =1)

In [23]:
x_test_transformed = np.concatenate((x_test_age,x_test_gender_city,x_test_cough,x_test_fever), axis =1)

In [24]:
x_train_transformed.shape

(80, 7)

#Execute the below one

In [32]:
#x_train_transformed

In [25]:
x_test_transformed

array([[ 27.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        , 100.        ],
       [  5.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  98.        ],
       [ 60.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        , 103.        ],
       [ 10.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  98.        ],
       [ 73.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  98.        ],
       [ 34.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        , 101.        ],
       [ 83.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  98.        ],
       [ 73.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        , 103.        ],
       [ 74.        ,   1.        ,   0.        ,   0.        ,
          1.    

Advanced Model

In [26]:
from sklearn.compose import ColumnTransformer

In [27]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
], remainder='passthrough')

In [28]:
transformer.fit_transform(x_train)


array([[100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [30]:
transformer.transform(x_test)


array([[100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.    

In [31]:
transformer.transform(x_test).shape

(20, 7)

In [32]:
transformer.transform(x_train).shape

(80, 7)